[package]
name = "tlru-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = "2"
tokio =  { version = "1.47.0", features = ["rt-multi-thread", "time"] }

[dev-dependencies]
tokio = { version = "1.47.0", features = ["rt-multi-thread", "time", "macros"] }  
